import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'

import {GoogleTagManager} from '@/libs/tracking/GoogleTagManager'
import {IS_GTM_ENABLED} from '@/libs/tracking/config.tracking'
import {RootInnerLayout} from '@/components/layout/RootInnerLayout'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {IS_GTM_ENABLED && <GoogleTagManager />}
        <RootInnerLayout>{children}</RootInnerLayout>
      </body>
    </html>
  )
}
