import type {Metadata} from 'next'
import {Mohave} from 'next/font/google'
import {cookies} from 'next/headers'

// Import env validation to ensure environment variables are validated early
import '../../env'

import {GoogleTagManager} from '@/lib/tracking/GoogleTagManager'
import {IS_GTM_ENABLED} from '@/lib/tracking/config.tracking'
import {RootInnerLayout} from '@/components/layout/RootInnerLayout'
import {getMenu, getCart} from '@/lib/shopify'

import '@/app/globals.css'

const mohave = Mohave({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-mohave',
})

// const overpassMono = Overpass_Mono({
//   subsets: ['latin'],
//   weight: ['300', '400', '500', '600', '700'],
//   variable: '--font-overpass-mono',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const menuPromise = getMenu('main-menu')
  const aboutMenuPromise = getMenu('footer-about')
  
  // Handle cart data server-side
  const cartId = (await cookies()).get('cartId')?.value
  const cartPromise = getCart(cartId)

  return (
    <html lang="en">
      <body className={`${mohave.className} antialiased`}>
        {IS_GTM_ENABLED && <GoogleTagManager />}
        <RootInnerLayout
          menuPromise={menuPromise}
          aboutMenuPromise={aboutMenuPromise}
          cartPromise={cartPromise}
        >
          {children}
        </RootInnerLayout>
      </body>
    </html>
  )
}
