import type {Metadata} from 'next'
import {Mohave} from 'next/font/google'

// Import env validation to ensure environment variables are validated early
import '../../env'

import {GoogleTagManager} from '@/libs/tracking/GoogleTagManager'
import {IS_GTM_ENABLED} from '@/libs/tracking/config.tracking'
import {RootInnerLayout} from '@/components/layout/RootInnerLayout'
import {getMenu} from '@/libs/shopify'

import '@/app/globals.css'

const mohave = Mohave({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-mohave',
})

// const overpassMono = Overpass_Mono({
//   subsets: ['latin'],
//   weight: ['300', '400', '500', '600', '700'],
//   variable: '--font-overpass-mono',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const menuPromise = getMenu('main-menu')
  const aboutMenuPromise = getMenu('footer-about')

  return (
    <html lang="en">
      <body className={`${mohave.className} antialiased`}>
        {IS_GTM_ENABLED && <GoogleTagManager />}
        <RootInnerLayout
          menuPromise={menuPromise}
          aboutMenuPromise={aboutMenuPromise}
        >
          {children}
        </RootInnerLayout>
      </body>
    </html>
  )
}
